config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'memberships/join'

  get 'tickets/buy'

  resources :bowlers
  

  get 'bowlers/new'

  



  resources :leagues, only: [:destroy]


  resources :leagues do
    member do
      get 'add'
    end
  end

  resources :tickets do
    member do
      get 'buy'
    end
  end

  resources :leagues do
    member do
      get 'draw'
    end
  end

  resources :memberships do
    member do
      get 'join'
    end
  end

  post "tickets/:id/buy" => "tickets#buy"
  post "leagues/:id/add" => "leagues#add"
  post "leagues/:id/draw" => "leagues#draw"
  post "memberships/:id/join" => "memberships#join"

  devise_for :users, controllers: { registrations: "registrations" }
 
end

app/models/league.rb
class League < ActiveRecord::Base
	
	# Validations
	validates :name, presence: true

	# Associations
	has_many :memberships 
 	has_many :bowlers, :through => :memberships
 	has_many :jackpots
 	has_many :tickets

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!  #Authenticate User before getting it
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
    @league = League.new #Create user in index
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league = League.find(params[:id]) #Find the League to show.

    @jackpot_league = @league.jackpots.first #Find the first jackpot related to the League

    @jackpots = @league.jackpots.recent_jackpot #Find all the Jackpots and order them

    @tickets = @league.tickets.recent_tickets #Find all the Tickets in League and Orden Them

    @members = @league.memberships #Find League Memberships
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end



  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)
    
    respond_to do |format|
      if @league.save
        @jackpot = @league.jackpots.create(jackpot_params)
        format.html { redirect_to leagues_path, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { redirect_to leagues_path, notice: 'League was not created.Please name your League first.' }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to leagues_path, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league} 
      else
        format.html { redirect_to leagues_path, notice: 'League was not updated.Please name your League first.' }

      end
    end

  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 

  # Function to Draw Winner
  def draw
    @league = League.find(params[:id]) #Current League

    @jackpot = Jackpot.find(params[:jackpot_id]) #Get Current Jackpot
    
    @winner = Ticket.pick_winner(@jackpot.id) #Get all the Tickets and Pick a Winner
    
    

    # If there is a Wiining ticket
    if @winner.present?
      @new_jackpot = Jackpot.new #Create a new Jackpot
      @new_jackpot.league_id = @league.id #The new Jackpot will belong to the League 
      @new_jackpot.balance = @winner[2] #Set balance to Old Balnce (Ticket Model)
      @new_jackpot.payout = @winner[3] #Set the Payout to the Winning_price (Ticket Model)
      @new_jackpot.save
    end

    # If there is a Winner Notify with a flash Message, if not notify that there are no Tickets in the jackpot. 
    if @winner.present?
      @win_bowler = bowler_winner(@winner[0].bowler_id)
      flash[:notice] = ["The winning Ticket id is: "]
      flash[:notice] << @winner[0].id
      flash[:notice] << ". The owner of the ticket is: "
      flash[:notice] << @win_bowler.name
      flash[:notice] << ". Strike:"
      flash[:notice] << @winner[1]
    else
      flash[:notice] = ["There is no tickets in the current Jackpot"]
    end

    redirect_to @league
  end

  # Get the Info from the Bowler who won. 
  def bowler_winner(id)
    win_bowler = Bowler.find_by_id(id) 
    return win_bowler
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :content, :membership_id)
    end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/_league.html.erb
          <div id="league_<%= league.id %>" >

            <div class="leagues col-sm-4"><!-- League Info -->

              <div class="border">
                <div class="leagues-holder">
                  <%= image_tag("league1.jpg", :alt => "League") %>
                  <div class="current-jackpot">League ID: <%= league.id %></div>
                </div>
                <div class="leagues-info">
                  <h1><%= league.name %></h1>
                  <p><%= league.content %></p>
                </div>

                  <div>
                   
                   <div class="league-login">
                    <%= link_to 'Show League', league_path(league), :class => "league-login-link" %>
                   </div>

                      <button type="button" class="league-login league-login-button" data-toggle="modal" data-target="#myupdateleague_<%= league.id %>">
                          Update
                      </button>
                   
                  </div>
                </div>

            </div><!-- League Info -->


            <!-- Modal - update posts -->
                  <%= form_for(league) do |f| %>
                  <div class="modal fade" id="myupdateleague_<%= league.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Update</h4>
                      </div>
                      <div class="modal-body">

                      <div class="field">
                        <%= f.label :name %><br>
                        <%= f.text_area :name , class: "form-control" %>
                      </div>
                      <div class="field">
                        <%= f.label :content %><br>
                        <%= f.text_area :content, class: "form-control" %>
                      </div>

                      </div>
                      <div class="modal-footer">
                        <button type="button" id="myupdatebutton_<%= league.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
                        <%= submit_tag "Update", class: "btn btn-primary" %>
                      </div>
                    </div>
                  </div>
                  </div>
                  <% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
    <div class="container">

      

        <!-- Section 1 App -->
        <div id="league-section-info">
          <h1 >Ready to have fun? </h1>
          <h4> Create your own League, add bowlers, buy tickets and get the change to win the Jackpot.
          </h4>
           <p id="notice"><%= notice %></p>
              
        </div>
        <div class="line-section"></div>

        <!-- Section 2 -->
        <div class="row" id="container_leagues">
          <button type="button" class="create-btn btn-large" data-toggle="modal" data-target="#mynewleague">
            New League
          </button>

          <%= render @leagues %>

        </div>



 <!-- Modal  create action -->
      <%= form_for(@league) do |f| %>
        <div class="modal fade" id="mynewleague" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Create a new League</h4>
            </div>
            
            <div class="modal-body">
              <div class="field">
                <%= f.label :name %><br>
                <%= f.text_field :name, class: "form-control post_title" %>
              </div>
              <div class="field">
                <%= f.label :content %><br>
                <%= f.text_area :content, class: "form-control post_content" %>
              </div>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
              <%= submit_tag "Create", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    <!-- Modal -->

app/views/leagues/join.html.erb
You join a team

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<div class="container"  id="league-info-holder">

  
    <div class="current-jackpot-league col-md-12">
      <h1><%= @league.name %></h1>

        
      <p> Jackpot Balance: </p>
      <p>
        <% current_jackpot = @league.jackpots.first %>
        <%= number_to_currency(current_jackpot.balance) %>  
      </p>

       <%= button_to "Draw Winner",  {:controller => "leagues", :action => "draw", :jackpot_id => current_jackpot.id}, :method => :post, :class => "draw-winner" %>

      <% if notice.kind_of?(Array) %>

         <%= flash[:notice].join(" ") %>
        
      <% end %>
      
    </div>


        <div class="holder col-sm-8">
          <!-- CURRENT BOWLERS -->
          <div >
            
            <div class="current-bowlers-league col-sm-12">
              <h3 class="league-title">Bowlers in this League</h3>
              
                <%if @members.present? %>
                  <% @members.each do |t| %>
                  <div class="col-sm-4">
                    <h6 class="bowlers-name"><%= t.name %> </h6>
                    <%= button_to 'Buy Ticket', {:controller => "tickets", :action => "buy", :ticket_id => t.bowler_id , :league_id => @league, :jackpot_id => @jackpot_league.id} , :method=>:post, :class => "buy-ticket"  %>
                    <br>
                  </div>
                  <% end %>
                <%else%>
                <div class="no-bowlers">
                    <h3>No Bowlers have joined this League</h3>
                    <%= link_to 'Join Bowlers', bowlers_path, :class => "draw-winner" %>
                </div>
                <%end%>
                  
                
            </div>
            <!-- HISTORY OF JACKPOTS -->
                <div class="jackpot-history col-sm-6">
                  <h3 class="league-title">Jackpot History</h3>

                    <% @jackpots.each do |j| %>

                       <% if (j == @jackpots.last ) == false %>
                          <div class="history-box">
                            <p class="box-jackpot">Jackpot id: <%= j.id%> 
                            <br>
                              PayOut:<%= number_to_currency(j.payout) %> 
                            <br>
                              Balance:<%= number_to_currency(j.balance) %> 
                            </p> 
                            <br>
                        </div>
                       <% end %>
                    <% end %>
                </div>

                
                <!-- HISTORY OF WINNING TICKETS -->
                 <div class="ticket-history col-sm-6">
                  <h3 class="league-title">History of Winning Tickets</h3>

                       <% @tickets.each do |x| %>

                         <%if x.status == true %>
                            <div class="history-box">
                              <p>
                                Ticket number <%= x.id %>
                                <br>
                                Winning Price: <%= number_to_currency(x.price) %>
                                <br>
                                Winner: <%= x.name%>
                                <br>
                                Strike: <%= x.strike%>
                              </p>
                                <br>
                            </div> 
                        <% end %>
                      <% end %>
                  </div>
            </div>
        </div>

          <!-- CURRENT TICKETS LEAGUE -->
          <div class="current-tickets-league col-sm-4">
            <h3 class="league-title right-title">Current Tickets in League</h3>

                    
                        <% @tickets.each  do |x| %>
                            <%if x.status == false %>
                              
                              <p class="ticket-holder">
                              Ticket number <%= x.id %>
                              <br>
                              Price: <%= number_to_currency(x.price) %>
                              <br>
                              Bowler Name:<%= x.name%>
                              </p>
                              <br>
                            <% end %>  
                            
                        <% end %> 



          </div>


          
          

         
</div>