config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'memberships/join'

  get 'tickets/buy'

  resources :bowlers
  

  get 'bowlers/new'

  



  resources :leagues, only: [:destroy]


  resources :leagues do
    member do
      get 'add'
    end
  end

  resources :tickets do
    member do
      get 'buy'
    end
  end

  resources :leagues do
    member do
      get 'draw'
    end
  end

  resources :memberships do
    member do
      get 'join'
    end
  end

  post "tickets/:id/buy" => "tickets#buy"
  post "leagues/:id/add" => "leagues#add"
  post "leagues/:id/draw" => "leagues#draw"
  post "memberships/:id/join" => "memberships#join"

  devise_for :users, controllers: { registrations: "registrations" }
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nextcapital</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <!-- FONTS -->
      <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

	<% if user_signed_in? %>

      <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
              <%= link_to image_tag("NC_logo.svg", :alt => "Next Capital Logo", :id => "logo_img"), root_path %>
           
                
              
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Leagues', leagues_path %></li>
                <li><%= link_to 'Bowlers', bowlers_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
	
	<% end %>

<%= yield %>

</body>
</html>